paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
       - Products
      responses:
        "200":
          description: 'Los productos fueron obtenidos correctamente'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: 'Error interno de servidor'
    post:
      summary: Crea un nuevo producto
      tags:
       - Products
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#components/requestBodies/createProduct' 
      responses: 
        "201":
          description: El producto fue creado exitosamente
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por PID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: PID del producto
          schema:
            type: string
      responses:
        "200":
          description: 'El producto fue obtenido correctamente'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: 'Producto no encontrado'
        "500":
          description: 'Error interno de servidor'
    put:
      summary: Actualiza un producto por PID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: PID del producto
          schema:
            type: string
      requestBody:
        description: Datos para actualizar el producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: 'El producto fue actualizado correctamente'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: 'Producto no encontrado'
        "500":
          description: 'Error interno de servidor'
    delete:
      summary: Elimina un producto por PID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: PID del producto
          schema:
            type: string
      responses:
        "200":
          description: 'El producto fue eliminado correctamente'
        "404":
          description: 'Producto no encontrado'
        "500":
          description: 'Error interno de servidor'
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado
        title:
          type: String
          description: Titulo de producto
        description:
          type: String
          description: Descripcion de producto
        thumbnail:
          type: String
          description: Rutas de las imagenes del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: Boolean
          description: Estado del producto
        category:
          type: String
          description: Categoria del Produtcto
        owner:
          type: String
          description: Usuario que creo el Produtcto 
      example:
        _id: ObjetID('66a9653785b5fdf966d15709')
        title: 'Producto 1'
        description: 'Descripcion del Producto 1'
        thumbnail: 'Sin Imagen'
        code: 'ABC-011'
        price: 36
        status: true
        category: 'Categoria 1'
        owner: '6686ddbb0e2fbbef41dc8e2a'
  requestBodies:
      createProduct:
        type: object
        properties:
          _id:
            type: ObjectId
            description: Id autogenerado
          title:
            type: String
            description: Titulo de producto
          description:
            type: String
            description: Descripcion de producto
          price:
            type: Number
            description: Precio del producto
          thumbnail:
            type: String
            description: Rutas de las imagenes del producto
          code:
            type: String
            description: Codigo de producto 
          stock:
            type: Number
            description: Stock del producto
          status:
            type: Boolean
            description: Estado del producto
          category:
            type: String
            description: Categoria del Produtcto
          owner:
            type: String
            description: Usuario que creo el Produtcto 
        example:
          title: 'Producto 100'
          description: 'Descripcion del Producto 100'
          price: 36
          thumbnail: 'Sin Imagen'
          code: 'abc123-151'
          stock: 45
          status: true
          category: 'Categoria 2'
          owner: '6686ddbb0e2fbbef41dc8e2a'
